/**
 * refs.js —— 真实文献索引库
 * ------------------------------------------------------------------
 * 赛题硬约束：参考论文严禁虚构。
 * 本库收录的均为公开可查证的真实论文/专著，字段含作者、标题、出处、年份。
 * `digest` 为人工整理的要点概述（非原文逐字引用），用于溯源比对演示；
 * 生产环境应替换为向量库中的原文切片（保留 page/offset 以便逐段核对）。
 */
const REFS = {
  R1:{a:'Li S., Jiang Q., Liu S., et al.',t:'A DNA nanorobot functions as a cancer therapeutic in response to a molecular trigger in vivo',v:'Nature Biotechnology, 36(3):258–264',y:2018,
      d:'DNA 折纸纳米机器人携带凝血酶，在小鼠模型中被肿瘤血管标志物触发后释放载荷，造成肿瘤内血栓并抑制生长，验证了体内条件触发式给药的可行性。'},
  R2:{a:'Soto F., Wang J., Ahmed R., Demirci U.',t:'Medical Micro/Nanorobots in Precision Medicine',v:'Advanced Science, 7(21):2002203',y:2020,
      d:'系统综述医用微纳机器人的驱动方式（磁、声、化学、生物混合）、成像追踪与生物相容性挑战，指出临床转化的主要缺口在动力持续性、体内定位与规模化制造。'},
  R3:{a:'Pardridge W. M.',t:'The blood–brain barrier: bottleneck in brain drug development',v:'NeuroRx, 2(1):3–14',y:2005,
      d:'指出约 98% 的小分子药物与几乎全部大分子药物无法穿过血脑屏障，是中枢神经系统给药的核心瓶颈。'},
  R4:{a:'Nelson B. J., Kaliakatsos I. K., Abbott J. J.',t:'Microrobots for Minimally Invasive Medicine',v:'Annual Review of Biomedical Engineering, 12:55–85',y:2010,
      d:'讨论微型机器人在微创医疗中的推进机制与尺度效应，指出在低雷诺数流体中传统推进方式失效，需要非往复式游动策略。'},
  R5:{a:'Sitti M.',t:'Miniature soft robots — road to the clinic',v:'Nature Reviews Materials, 3:74–75',y:2018,
      d:'评述软体微型机器人走向临床所需的可降解材料、体内成像与安全性证据链。'},
  R6:{a:'Flynn J. R.',t:'Massive IQ gains in 14 nations: What IQ tests really measure',v:'Psychological Bulletin, 101(2):171–191',y:1987,
      d:'记录 14 个国家在 20 世纪出现的大幅 IQ 分数上升（弗林效应），并论证其更可能反映抽象思维训练与测验熟悉度，而非一般智力实质提升。'},
  R7:{a:'Bratsberg B., Rogeberg O.',t:'Flynn effect and its reversal are both environmentally caused',v:'PNAS, 115(26):6674–6678',y:2018,
      d:'基于挪威兄弟内部（within-family）设计发现弗林效应在 1975 年后出生队列出现逆转，且逆转发生在家庭内部，支持环境成因而非人口构成变化。'},
  R8:{a:'Plomin R., von Stumm S.',t:'The new genetics of intelligence',v:'Nature Reviews Genetics, 19:148–159',y:2018,
      d:'综述智力的多基因结构：遗传度随年龄升高至成年约 50%–70%，但单个位点效应极小，多基因评分目前仅能解释小部分个体差异。'},
  R9:{a:'Butlin P., Long R., Elmoznino E., et al.',t:'Consciousness in Artificial Intelligence: Insights from the Science of Consciousness',v:'arXiv:2308.08708',y:2023,
      d:'提出以主流意识科学理论（全局工作空间、高阶理论、注意图式等）导出"指标属性"清单，用以评估现有 AI 系统；结论是当前系统未满足多数指标，但不存在明显的技术阻断。'},
  R10:{a:'Tononi G., Boly M., Massimini M., Koch C.',t:'Integrated information theory: from consciousness to its physical substrate',v:'Nature Reviews Neuroscience, 17:450–461',y:2016,
      d:'整合信息论（IIT）主张意识对应系统整合信息量 Φ，并推论前馈架构（如典型深度网络）的 Φ 近似为零。'},
  R11:{a:'Dehaene S., Lau H., Kouider S.',t:'What is consciousness, and could machines have it?',v:'Science, 358(6362):486–492',y:2017,
      d:'将意识拆分为全局可用性（C1）与自我监控（C2）两类可操作计算功能，认为二者原则上可由机器实现，但现有系统主要停留在无意识加工层面。'},
  R12:{a:'Chalmers D. J.',t:'Facing up to the problem of consciousness',v:'Journal of Consciousness Studies, 2(3):200–219',y:1995,
      d:'提出意识的"难问题"：解释功能与行为之外，为何会存在主观体验，指出功能性解释无法直接跨越该鸿沟。'},
  R13:{a:'Frey C. B., Osborne M. A.',t:'The future of employment: How susceptible are jobs to computerisation?',v:'Technological Forecasting and Social Change, 114:254–280',y:2017,
      d:'以任务可编码性建模估计美国约 47% 就业岗位处于高自动化风险区间；方法基于职业层面判定，后续研究指出其可能高估。'},
  R14:{a:'Eloundou T., Manning S., Mishkin P., Rock D.',t:'GPTs are GPTs: Labor market impact potential of large language models',v:'arXiv:2303.10130 / Science (2024)',y:2023,
      d:'以任务为单位评估 LLM 暴露度，估计约 80% 美国劳动者至少 10% 的工作任务受影响、约 19% 劳动者有 50% 以上任务受影响，强调是"暴露"而非"替代"。'},
  R15:{a:'Acemoglu D., Restrepo P.',t:'Robots and Jobs: Evidence from US Labor Markets',v:'Journal of Political Economy, 128(6):2188–2244',y:2020,
      d:'利用地区通勤区暴露度识别工业机器人对就业与工资的负向效应，估计每千名工人增加一台机器人使就业人口比下降约 0.2 个百分点。'},
  R16:{a:'Autor D. H.',t:'Why Are There Still So Many Jobs? The History and Future of Workplace Automation',v:'Journal of Economic Perspectives, 29(3):3–30',y:2015,
      d:'指出自动化同时产生替代效应与互补效应，波兰尼悖论（我们知道的多于能言说的）限制了隐性知识任务的自动化。'},
  R17:{a:'Brynjolfsson E., Li D., Raymond L.',t:'Generative AI at Work',v:'NBER Working Paper 31161 / Quarterly Journal of Economics',y:2023,
      d:'客服场景现场实验显示生成式 AI 助手使平均问题解决量提升约 14%，且对新手与低技能员工提升最大，呈现能力压缩效应。'},
  R18:{a:'Hochberg L. R., Bacher D., Jarosiewicz B., et al.',t:'Reach and grasp by people with tetraplegia using a neurally controlled robotic arm',v:'Nature, 485:372–375',y:2012,
      d:'四肢瘫痪受试者通过植入式皮层电极阵列控制机械臂完成三维伸手抓取与自主饮水，证明侵入式 BCI 的实用控制能力。'},
  R19:{a:'Willett F. R., Avansino D. T., Hochberg L. R., Henderson J. M., Shenoy K. V.',t:'High-performance brain-to-text communication via handwriting',v:'Nature, 593:249–254',y:2021,
      d:'通过解码想象手写的皮层活动实现约 90 字符/分钟、原始准确率约 94% 的脑到文本通信，显著优于此前点选式方案。'},
  R20:{a:'Lebedev M. A., Nicolelis M. A. L.',t:'Brain-Machine Interfaces: From Basic Science to Neuroprostheses and Neurorehabilitation',v:'Physiological Reviews, 97(2):767–837',y:2017,
      d:'系统综述 BMI 的信号获取、解码算法与长期稳定性问题，指出电极胶质瘢痕与信号漂移是慢性植入的主要障碍。'},
  R21:{a:'Doudna J. A., Charpentier E.',t:'The new frontier of genome engineering with CRISPR-Cas9',v:'Science, 346(6213):1258096',y:2014,
      d:'综述 CRISPR-Cas9 的机制与应用边界，强调脱靶效应与生殖系编辑的伦理约束。'},
  R22:{a:'Rubenstein M., Cornejo A., Nagpal R.',t:'Programmable self-assembly in a thousand-robot swarm',v:'Science, 345(6198):795–799',y:2014,
      d:'1024 台 Kilobot 机器人仅依靠局部通信与三条简单规则（边缘跟随、梯度形成、定位）自组装成指定二维形状，展示大规模群体的涌现协调。'},
  R23:{a:'Woolley A. W., Chabris C. F., Pentland A., Hashmi N., Malone T. W.',t:'Evidence for a Collective Intelligence Factor in the Performance of Human Groups',v:'Science, 330(6004):686–688',y:2010,
      d:'发现群体存在类似个体 g 因子的集体智力因子 c，其与成员平均智商相关较弱，而与社会敏感度、发言均衡度、女性比例显著相关。'},
  R24:{a:'Reynolds C. W.',t:'Flocks, herds and schools: A distributed behavioral model',v:'ACM SIGGRAPH Computer Graphics, 21(4):25–34',y:1987,
      d:'提出 Boids 模型：分离、对齐、聚合三条局部规则即可产生逼真的群体集群行为，是涌现研究的经典基线。'},
  R25:{a:'Bonabeau E., Dorigo M., Theraulaz G.',t:'Swarm Intelligence: From Natural to Artificial Systems',v:'Oxford University Press',y:1999,
      d:'系统建立群体智能的自组织框架：正反馈、负反馈、随机涨落与多重交互四要素共同驱动涌现。'},
  R26:{a:'Dorigo M., Birattari M., Stützle T.',t:'Ant Colony Optimization',v:'IEEE Computational Intelligence Magazine, 1(4):28–39',y:2006,
      d:'蚁群算法综述：信息素间接通信（stigmergy）如何把局部随机搜索转化为全局组合优化能力。'},
  R27:{a:'Silver D., Huang A., Maddison C. J., et al.',t:'Mastering the game of Go with deep neural networks and tree search',v:'Nature, 529:484–489',y:2016,
      d:'AlphaGo 结合策略网络、价值网络与蒙特卡洛树搜索击败人类职业棋手，其部分着法（如第二局第 37 手）超出人类既有棋理。'},
  R28:{a:'Silver D., Schrittwieser J., Simonyan K., et al.',t:'Mastering the game of Go without human knowledge',v:'Nature, 550:354–359',y:2017,
      d:'AlphaGo Zero 完全由自我博弈从零学习，无需人类棋谱即超越前代，说明新颖策略可在封闭规则空间内自主涌现。'},
  R29:{a:'Romera-Paredes B., Barekatain M., Novikov A., et al.',t:'Mathematical discoveries from program search with large language models',v:'Nature, 625:468–475',y:2024,
      d:'FunSearch 将 LLM 与进化式程序搜索结合，在 cap set 问题上发现优于既有构造的新解，并改进装箱启发式，展示可验证域中的真实新发现。'},
  R30:{a:'Boden M. A.',t:'The Creative Mind: Myths and Mechanisms (2nd ed.)',v:'Routledge',y:2004,
      d:'区分组合式、探索式与变革式三类创造力，指出变革式创造需要改变概念空间本身的规则，是机器创造力最难的一层。'},
  R31:{a:'Biamonte J., Wittek P., Pancotti N., et al.',t:'Quantum machine learning',v:'Nature, 549:195–202',y:2017,
      d:'综述量子机器学习的潜在加速来源与四大障碍：输入问题、输出问题、成本函数问题与基准比较问题。'},
  R32:{a:'Preskill J.',t:'Quantum Computing in the NISQ era and beyond',v:'Quantum, 2:79',y:2018,
      d:'提出 NISQ 概念：50–数百量子比特、无完整纠错的含噪中等规模设备，其可解决问题范围有限且需谨慎评估量子优势主张。'},
  R33:{a:'Markram H., Muller E., Ramaswamy S., et al.',t:'Reconstruction and Simulation of Neocortical Microcircuitry',v:'Cell, 163(2):456–492',y:2015,
      d:'重建约 31,000 个神经元、约 3,700 万个突触的大鼠体感皮层微环路并进行数字仿真，展示了生物细节级仿真的计算代价。'},
  R34:{a:'Pei J., Deng L., Song S., et al.',t:'Towards artificial general intelligence with hybrid Tianjic chip architecture',v:'Nature, 572:106–111',y:2019,
      d:'清华"天机芯"异构融合类脑芯片，同时支持脉冲神经网络与人工神经网络范式，在无人自行车上完成多模态实时控制。'},
  R35:{a:'Merolla P. A., Arthur J. V., Alvarez-Icaza R., et al.',t:'A million spiking-neuron integrated circuit with a scalable communication network and interface',v:'Science, 345(6197):668–673',y:2014,
      d:'IBM TrueNorth 类脑芯片集成 100 万脉冲神经元、2.56 亿突触，实时运行功耗约 70 mW，展示事件驱动计算的能效优势。'},
  R36:{a:'Hassabis D., Kumaran D., Summerfield C., Botvinick M.',t:'Neuroscience-Inspired Artificial Intelligence',v:'Neuron, 95(2):245–258',y:2017,
      d:'论证神经科学对 AI 的两重价值：提供算法灵感与提供验证约束，并指出双向借鉴的具体路径。'},
  R37:{a:'Wang H., Fu T., Du Y., et al.',t:'Scientific discovery in the age of artificial intelligence',v:'Nature, 620:47–60',y:2023,
      d:'综述 AI 在科学发现全流程（假设生成、实验设计、数据分析）的应用格局，强调可解释性、数据质量与人机协作是落地关键。'},
  R38:{a:'Lu C., Lu C., Lange R. T., Foerster J., Clune J., Ha D.',t:'The AI Scientist: Towards Fully Automated Open-Ended Scientific Discovery',v:'arXiv:2408.06292',y:2024,
      d:'提出端到端自动科研框架（构思—编码—实验—写作—评审），同时报告其局限：想法新颖性有限、存在实现错误与评审偏差。'},
  R39:{a:'Boiko D. A., MacKnight R., Kline B., Gomes G.',t:'Autonomous chemical research with large language models',v:'Nature, 624:570–578',y:2023,
      d:'Coscientist 系统由 LLM 驱动检索、规划并操作云实验室完成钯催化交叉偶联反应优化，验证了闭环自主实验的可行性。'},
  R40:{a:'Du Y., Li S., Torralba A., Tenenbaum J. B., Mordatch I.',t:'Improving Factuality and Reasoning in Language Models through Multiagent Debate',v:'ICML 2024 / arXiv:2305.14325',y:2023,
      d:'多个语言模型实例互相辩论并迭代修正答案，在数学与事实任务上显著提升准确率并减少幻觉。'},
  R41:{a:'Lewis P., Perez E., Piktus A., et al.',t:'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',v:'NeurIPS 2020',y:2020,
      d:'提出 RAG 架构：将参数化知识与可检索的非参数化知识结合，提升知识密集任务的事实性并支持来源溯源。'},
  R42:{a:'Yao S., Zhao J., Yu D., et al.',t:'ReAct: Synergizing Reasoning and Acting in Language Models',v:'ICLR 2023',y:2023,
      d:'交替生成推理轨迹与外部动作，使模型能调用工具核查事实，降低推理链幻觉。'},
  R43:{a:'Ji Z., Lee N., Frieske R., et al.',t:'Survey of Hallucination in Natural Language Generation',v:'ACM Computing Surveys, 55(12):1–38',y:2023,
      d:'系统梳理生成式模型幻觉的来源（数据、训练、解码）与缓解手段，指出溯源式约束是当前最可操作的路径之一。'},
  R44:{a:'Pearl J.',t:'Causality: Models, Reasoning, and Inference (2nd ed.)',v:'Cambridge University Press',y:2009,
      d:'建立因果推断的结构化框架（do-算子、后门准则），明确统计相关不等于因果，需要因果图与识别条件支撑。'},
  R45:{a:'Legg S., Hutter M.',t:'Universal Intelligence: A Definition of Machine Intelligence',v:'Minds and Machines, 17(4):391–444',y:2007,
      d:'把智能形式化为在所有可计算环境中获得奖励的加权期望能力，为跨物种/跨系统的智能上限讨论提供了度量框架。'},
  R46:{a:'Qwen Team, Alibaba Group',t:'Qwen2.5 Technical Report',v:'arXiv:2412.15115',y:2024,
      d:'介绍 Qwen2.5 系列开源模型的预训练语料规模、后训练策略与在推理、代码、多语言基准上的表现。'},
  R47:{a:'Qwen Team, Alibaba Group',t:'Qwen3 Technical Report',v:'arXiv:2505.09388',y:2025,
      d:'介绍 Qwen3 系列的混合思考模式（thinking / non-thinking）与 MoE 架构设计，支持在推理深度与成本之间动态权衡。'}
};

/** 生成参考文献显示文本 */
function refText(id){
  const r = REFS[id];
  if(!r) return id;
  return `${r.a} ${r.t}. ${r.v}, ${r.y}.`;
}
